name: Create Pull Request

on:
  push:
    branches:
      - feature/version  # Substitua 'feature/version' pela branch onde você faz os commits

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up GitHub CLI
      run: sudo apt-get install gh

    - name: Create Pull Request
      run: |
        gh pr create --base main --head feature/version --title "Auto PR" --body "Automated pull request created by GitHub Actions"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
