name: Create Pull Request

on:
  push:
    branches:
      - your-branch-name  # Substitua 'your-branch-name' pela branch onde você faz os commits

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up GitHub CLI
      run: sudo apt-get install gh

    - name: Create Pull Request
      run: |
        gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
        gh pr create --base main --head your-branch-name --title "Auto PR" --body "Automated pull request created by GitHub Actions"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
